[app_settings]
app_version = "0.1.0"
app_name = "image cloude"
app_host = "0.0.0.0"
app_port = 8000


[db_settings]
db_name = "postgres"
db_user = "user"
db_password = "password"
db_host = "localhost"
db_port = 5432


[auth_settings]
sekret_key = "mipt"
algorithm = "HS256"
access_token_expire_minutes = 30